### ISSUE TITLE
[Engie] Verificação do uso da direção do Fasor para Plot da Orbita

### ISSUE THREAD

**Issue by CemachMD** [md-monitoracao-diagnose/MDM_287#11]
Foi solicitado pela Engie a verificação do uso da direção do Fasor para Plot da Orbita.

A principio se observa que o fasor é somente utilizado para determinar o corte dos sinais por volta para gráfica a orbita. Em algumas ferramentas a informação da posição/angulo do fasor determina o Zero do gráfico, conseguindo manter o formato da órbita mesmo trocando de posição real do fasor.

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MDM] Verificação do uso do sentido de rotação na órbita](https://trello.com/c/39txrFKu/21-mdm-verifica%C3%A7%C3%A3o-do-uso-do-sentido-de-rota%C3%A7%C3%A3o-na-%C3%B3rbita)

**Comment by esquioga** [comment]
É utilizado o par de pontos presente no plano de medição. O eixo que representarão no gráfico é definido pela direção do ponto, se for igual a 0 será utilizado no eixo x e outros valores no eixo y.
