### ISSUE TITLE
UHE Capivara - Esgotamento de Memória ocasionado pelo SQL e MDM

### ISSUE THREAD

**Issue by danielpinheiro07** [md-monitoracao-diagnose/MDM_287#15]
@felipe-coutto Copiei você em e-mail sobre o problema que identifiquei na UHE Capivara após solicitação do Marco.
Esta ocorrendo grande consumo de memória pelo SQL e o MDM, que esta gerando erro quando são geradas ferramentas com grande quantidade de registros (em anexo seguem 2 prints para exemplificar melhor).
Eles estão realizando algumas manobras na UG, então dentro das possibilidades, seria importante priorizar esta solicitação.
Qualquer coisa me informe.
![memoria cheia](https://user-images.githubusercontent.com/39570831/42294110-ffb274ec-7fb4-11e8-8961-59162fc3c410.png)
![memoria cheia1](https://user-images.githubusercontent.com/39570831/42294111-ffdb077c-7fb4-11e8-95f6-f8e923c04fcd.png)

**Comment by felipe-coutto** [comment]
Lógica de trigger corrigida e atualização implantada em UHE Capivara
