### ISSUE TITLE
SAE - Incluir tipos de sensor

### ISSUE THREAD

**Issue by danielpinheiro07** [md-monitoracao-diagnose/MDM_287#24]
Segue abaixo lista dos tipos de sensor a serem incluídos no MDM de SAE.
- mN/m - Tensão Interfacial
- g/ml - Densidade Relativa
- mg/kg - PCB
- mg/l - físico-químico

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SAE] Limpeza de bugs para apresentação](https://trello.com/c/N5FD8oNU/15-sae-limpeza-de-bugs-para-apresenta%C3%A7%C3%A3o)

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SAE] Limpeza de bugs para apresentação](https://trello.com/c/N5FD8oNU/15-sae-limpeza-de-bugs-para-apresenta%C3%A7%C3%A3o)

**Comment by thiagopaiva-md** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SAE] Limpeza de bugs para apresentação](https://trello.com/c/N5FD8oNU/15-sae-limpeza-de-bugs-para-apresenta%C3%A7%C3%A3o)

**Comment by thiagopaiva-md** [comment]
Incluído no build 70.
