### ISSUE TITLE
Erro ao Enviar comando "Atualizar" - CPFL - CMA

### ISSUE THREAD

**Issue by fernandocsmd** [md-monitoracao-diagnose/MDM_287#31]
Atualizando os canais do MDM no CMA da CPFL, acontece Erro ao enviar o comando "Atualizar" em:

 Registros> Analise Automática> Atualizar

![image](https://user-images.githubusercontent.com/42279122/44491043-605db980-a636-11e8-9acb-d183fd2a6569.png)

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CPFL] Recuperar conectividade com PCHs offline](https://trello.com/c/ZioTEYaC/42-cpfl-recuperar-conectividade-com-pchs-offline)

**Comment by felipe-coutto** [comment]
Problema de configuração. O equipamento UG01 estava cadastrado para utilizar POT_AT e QUEDA como pontos de operação, mas QUEDA estava sem canal configurado, portanto sendo considerado um ponto offline. Assim, na hora de gerar a configuração o erro acontecia. A gerdaq.dll foi atualizada para prover mensagem de erro mais clara.
